// 30 jours de contenu KONVWA. Chaque entrée = une image (1080x1350) + sa légende.
// Aucune statistique ni promesse inventée : seulement ce que fait réellement l'application.
const H = '#KONVWA #Haïti #ImportationHaïti';
module.exports = [
  { day: 1, type: 'hero', theme: 'white', head: 'Importez depuis <b>Alibaba, Shein</b> et <b>Temu</b> vers <em>Haïti</em>', sub: 'Un devis clair, un suivi jusqu\'à votre porte. Sans carte bancaire étrangère.', pay: true,
    caption: 'Bienvenue sur KONVWA 🇭🇹 Importez depuis Alibaba, Shein et Temu, payez en gourdes avec MonCash ou NatCash et suivez votre colis jusqu\'à votre porte. Créez votre compte sur konvwa.shop', tags: `${H} #Alibaba #Shein #Temu #MonCash #NatCash` },
  { day: 2, type: 'steps', theme: 'white', tag: 'Comment ça marche', title: 'Commander en <em>4 étapes</em>', steps: [
      ['Collez le lien', 'Envoyez le lien du produit Alibaba, Shein ou Temu.'],
      ['Recevez votre devis', 'Tous les frais sont détaillés, rien de caché.'],
      ['Payez en gourdes', 'Avec MonCash, NatCash ou votre portefeuille KONVWA.'],
      ['Suivez votre colis', 'De l\'achat jusqu\'à la livraison, étape par étape.'] ],
    caption: 'Commander sur KONVWA, c\'est simple : 1) collez le lien, 2) recevez votre devis, 3) payez en gourdes, 4) suivez votre colis. 👉 konvwa.shop', tags: `${H} #CommentCaMarche` },
  { day: 3, type: 'feature', theme: 'navy', icon: 'wallet', tag: 'Paiement local', title: 'Pas de carte bancaire <em>étrangère</em>', body: 'Payez directement depuis Haïti, en gourdes (HTG), avec MonCash ou NatCash.', bullets: ['MonCash', 'NatCash', 'Portefeuille KONVWA'],
    caption: 'Plus besoin de carte bancaire étrangère pour acheter à l\'international. Sur KONVWA, vous payez en gourdes avec MonCash ou NatCash. 💳➡️🇭🇹', tags: `${H} #MonCash #NatCash` },
  { day: 4, type: 'feature', theme: 'white', icon: 'receipt', tag: 'Transparence', title: 'Un devis <em>clair</em>, sans surprise', body: 'Chaque devis détaille les frais : produit, frais de traitement, expédition. Vous savez ce que vous payez avant de payer.', bullets: ['Frais détaillés', 'Montant en HTG', 'Vous acceptez ou refusez'],
    caption: 'Chez KONVWA, vous voyez chaque frais avant de payer. Vous acceptez le devis… ou vous le refusez. C\'est vous qui décidez. 🧾', tags: `${H} #Transparence` },
  { day: 5, type: 'compare', theme: 'white', tag: 'Expédition', title: 'Tout inclus ou <em>séparé</em> ?', left: ['Tout inclus', ['Un seul paiement', 'Le transport est calculé dans le devis', 'Idéal pour aller vite']], right: ['Expédition séparée', ['Vous payez l\'achat d\'abord', 'L\'expédition est calculée à l\'arrivée au dépôt', 'Frais selon le poids et le volume réels']],
    caption: 'Deux façons de commander : « Tout inclus » (un seul paiement) ou « Expédition séparée » (vous payez l\'achat, puis l\'expédition une fois le colis pesé au dépôt). À vous de choisir ! ⚖️', tags: `${H} #Expédition` },
  { day: 6, type: 'feature', theme: 'orange', icon: 'truck', tag: 'Suivi', title: 'Suivez votre colis <em>à chaque étape</em>', body: 'Achat, dépôt, expédition, douane, livraison : vous voyez où en est votre commande depuis votre tableau de bord.', bullets: ['Étapes claires', 'Historique complet', 'Toujours à jour'],
    caption: 'Où est mon colis ? Sur KONVWA, vous le voyez en un coup d\'œil : chaque étape est mise à jour dans votre tableau de bord. 📦➡️🚚', tags: `${H} #Suivi` },
  { day: 7, type: 'tips', theme: 'white', tag: 'Conseils', title: '5 réflexes pour <em>bien commander</em>', items: ['Vérifiez le lien du produit avant de l\'envoyer', 'Choisissez la bonne taille, couleur et quantité', 'Lisez le devis en entier avant de payer', 'Gardez votre numéro de commande', 'Activez les notifications pour suivre votre colis'],
    caption: '5 réflexes simples pour commander sereinement sur KONVWA. Lequel vous manquait ? 👇', tags: `${H} #Conseils` },
  { day: 8, type: 'hero', theme: 'navy', head: 'Payez en gourdes avec <em>MonCash</em> et <em>NatCash</em>', sub: 'Vos achats internationaux, enfin accessibles depuis Haïti.', pay: false,
    caption: 'MonCash, NatCash : vos moyens de paiement habituels, pour acheter partout dans le monde via KONVWA. 🌍', tags: `${H} #MonCash #NatCash` },
  { day: 9, type: 'feature', theme: 'navy', icon: 'wallet', tag: 'Portefeuille', title: 'Votre portefeuille <em>KONVWA</em>', body: 'Rechargez une fois, payez vos commandes en un clic et gardez l\'historique de chaque transaction.', bullets: ['Solde visible en HTG', 'Historique complet', 'Paiement en un clic'],
    caption: 'Votre portefeuille KONVWA : rechargez, payez en un clic et retrouvez toutes vos transactions. 👛', tags: `${H} #Portefeuille` },
  { day: 10, type: 'steps', theme: 'orange', tag: 'Portefeuille', title: 'Recharger en <em>3 étapes</em>', steps: [
      ['Ouvrez Portefeuille', 'Depuis votre tableau de bord.'],
      ['Choisissez le montant', 'Et votre moyen de paiement.'],
      ['Confirmez', 'Votre solde est crédité après validation.'] ],
    caption: 'Recharger son portefeuille KONVWA ? 3 étapes, c\'est tout. 👛', tags: `${H} #Portefeuille` },
  { day: 11, type: 'faq', theme: 'white', tag: 'Question fréquente', q: 'Combien de temps pour recevoir mon devis ?', a: 'Vous recevez votre devis rapidement, en général sous 24 heures. Vous êtes prévenu par notification dès qu\'il est prêt.',
    caption: 'Question fréquente : combien de temps pour recevoir mon devis ? En général, sous 24 h. Vous êtes notifié dès qu\'il est prêt. 🔔', tags: `${H} #FAQ` },
  { day: 12, type: 'feature', theme: 'white', icon: 'camera', tag: 'Confiance', title: 'Des <em>photos</em> de votre colis', body: 'À son arrivée au dépôt, votre colis est photographié. Vous voyez dans quel état il se trouve.', bullets: ['Photos au dépôt', 'Visibles dans l\'appli', 'Pour votre tranquillité'],
    caption: 'Votre colis est arrivé au dépôt ? Vous recevez des photos pour constater son état. 📸', tags: `${H} #Confiance` },
  { day: 13, type: 'feature', theme: 'navy', icon: 'shield', tag: 'Protection', title: 'Assurez votre <em>expédition</em>', body: 'Protégez la valeur de vos colis avec l\'assurance optionnelle, achetée en quelques secondes depuis l\'application.', bullets: ['Optionnelle', 'Achat en un clic', 'Frais calculés pour vous'],
    caption: 'Un colis de valeur ? Ajoutez l\'assurance KONVWA en un clic, directement depuis l\'application. 🛡️', tags: `${H} #Assurance` },
  { day: 14, type: 'feature', theme: 'orange', icon: 'lock', tag: 'Tarif sécurisé', title: 'Votre <em>taux</em> est figé', body: 'Le taux de change appliqué à votre devis est bloqué : il ne change pas entre l\'acceptation et le paiement.', bullets: ['Taux bloqué', 'Pas de mauvaise surprise', 'Montant final connu'],
    caption: 'Le taux de change de votre devis est figé : le montant que vous voyez est celui que vous payez. 🔒', tags: `${H} #Taux` },
  { day: 15, type: 'hero', theme: 'white', head: 'Gros achats sur <b>Alibaba</b> ? On s\'en <em>occupe</em>', sub: 'Du fournisseur chinois jusqu\'à Haïti, vous gardez le contrôle.', pay: true,
    caption: 'Vous achetez en quantité sur Alibaba ? KONVWA gère l\'achat, le transport et le suivi pour vous. 📦', tags: `${H} #Alibaba` },
  { day: 16, type: 'tips', theme: 'navy', tag: 'Alibaba', title: 'Acheter sur <em>Alibaba</em> : les bons réflexes', items: ['Regardez la quantité minimum de commande', 'Comparez plusieurs fournisseurs', 'Vérifiez les avis et la fiche du vendeur', 'Précisez la variante exacte voulue', 'Envoyez le lien, on calcule tout pour vous'],
    caption: 'Alibaba, mode d\'emploi : nos 5 réflexes pour acheter malin. Envoyez-nous le lien, on s\'occupe du reste. 🧠', tags: `${H} #Alibaba #Conseils` },
  { day: 17, type: 'tips', theme: 'white', tag: 'Shein & Temu', title: 'Shein et Temu : <em>commandez malin</em>', items: ['Vérifiez le guide des tailles avant de choisir', 'Regroupez vos articles pour optimiser l\'expédition', 'Contrôlez couleur et quantité dans le lien', 'Gardez le lien exact du panier ou du produit', 'Suivez l\'arrivée depuis votre tableau de bord'],
    caption: 'Shein, Temu : 5 astuces pour commander sans erreur et optimiser vos envois. 🛍️', tags: `${H} #Shein #Temu #Conseils` },
  { day: 18, type: 'feature', theme: 'white', icon: 'tag', tag: 'Flexibilité', title: 'Payez en <em>plusieurs fois</em>', body: 'Étalez le paiement de certaines commandes en plusieurs versements, directement depuis votre portefeuille.', bullets: ['Versements échelonnés', 'Suivi de chaque échéance', 'Disponible sur certaines commandes'],
    caption: 'Un gros achat ? Étalez le paiement en plusieurs versements, depuis votre portefeuille KONVWA. 💸', tags: `${H} #PaiementEnPlusieursFois` },
  { day: 19, type: 'steps', theme: 'white', tag: 'Cargaison', title: 'Vous avez déjà <em>vos colis</em> ?', steps: [
      ['Faites une demande d\'expédition', 'Indiquez l\'origine, le nombre de colis, le poids estimé.'],
      ['Recevez votre tarif', 'Calculé selon le poids et le volume réels.'],
      ['Payez l\'expédition', 'En gourdes, depuis l\'application.'],
      ['Suivez le transport', 'Votre colis voyage avec un lot d\'expédition.'] ],
    caption: 'Vos marchandises sont déjà prêtes ? Envoyez-les avec KONVWA : demande d\'expédition, tarif clair, suivi complet. 🚢', tags: `${H} #Cargaison #Expédition` },
  { day: 20, type: 'feature', theme: 'orange', icon: 'pin', tag: 'Livraison', title: 'Récupérez ou faites <em>livrer</em>', body: 'Choisissez la livraison à votre adresse ou un point de retrait selon votre région en Haïti.', bullets: ['Livraison à domicile', 'Points de retrait', 'Selon votre région'],
    caption: 'À la maison ou en point de retrait : choisissez ce qui vous arrange selon votre région. 📍', tags: `${H} #Livraison` },
  { day: 21, type: 'feature', theme: 'white', icon: 'users', tag: 'Parrainage', title: 'Parrainez vos <em>proches</em>', body: 'Partagez votre code personnel avec vos amis. Retrouvez-le dans votre espace client.', bullets: ['Un code personnel', 'À partager facilement', 'Dans votre espace client'],
    caption: 'Vous aimez KONVWA ? Partagez votre code de parrainage avec vos amis. 🤝', tags: `${H} #Parrainage` },
  { day: 22, type: 'feature', theme: 'navy', icon: 'shield', tag: 'Sécurité', title: 'Votre compte est <em>protégé</em>', body: 'Double authentification, connexion par empreinte ou appareil (passkey), appareils de confiance : votre argent est protégé.', bullets: ['Double authentification', 'Connexion par passkey', 'Appareils de confiance'],
    caption: 'Sécurité : double authentification, passkey, appareils de confiance. Votre compte et votre portefeuille sont protégés. 🔐', tags: `${H} #Sécurité` },
  { day: 23, type: 'feature', theme: 'white', icon: 'bell', tag: 'Notifications', title: 'Restez <em>informé</em> en temps réel', body: 'Devis prêt, colis arrivé, paiement confirmé : vous êtes prévenu, et un clic vous amène à la bonne page.', bullets: ['Cloche de notifications', 'Notifications push', 'Lien direct vers l\'action'],
    caption: 'Un devis prêt, un colis arrivé ? Vous êtes notifié instantanément. 🔔', tags: `${H} #Notifications` },
  { day: 24, type: 'feature', theme: 'orange', icon: 'phone', tag: 'Application', title: 'Installez KONVWA sur votre <em>téléphone</em>', body: 'Ajoutez l\'application à votre écran d\'accueil : elle s\'ouvre en un clic, comme une vraie appli.', bullets: ['Sans téléchargement lourd', 'Icône sur l\'écran d\'accueil', 'iPhone et Android'],
    caption: 'Ajoutez KONVWA à l\'écran d\'accueil de votre téléphone : accès direct, expérience appli. 📱', tags: `${H} #Application` },
  { day: 25, type: 'feature', theme: 'navy', icon: 'globe', tag: 'Langues', title: 'Français ou <em>English</em>', body: 'L\'interface existe en deux langues, et un mode sombre est disponible pour votre confort.', bullets: ['Français', 'English', 'Mode clair et sombre'],
    caption: 'KONVWA parle français et English, avec un mode sombre pour vos yeux. 🌙', tags: `${H} #English #ModeSombre` },
  { day: 26, type: 'feature', theme: 'white', icon: 'box', tag: 'Revendeurs', title: 'Vous <em>revendez</em> ? Parlons prix', body: 'Le statut revendeur ouvre l\'accès au catalogue de gros et à des prix dégressifs selon la quantité.', bullets: ['Catalogue de gros', 'Prix dégressifs', 'Tableau de ventes'],
    caption: 'Commerçants et revendeurs : demandez le statut revendeur pour accéder au catalogue de gros et aux prix dégressifs. 🏪', tags: `${H} #Revendeur #Commerce` },
  { day: 27, type: 'faq', theme: 'navy', tag: 'Question fréquente', q: 'Quels sont les frais ?', a: 'Chaque devis détaille le prix du produit, les frais et l\'expédition. Vous voyez le total en gourdes avant de payer.',
    caption: 'Quels frais sur KONVWA ? Tout est détaillé dans le devis : produit, frais, expédition. Total en gourdes, avant paiement. 🧾', tags: `${H} #FAQ` },
  { day: 28, type: 'faq', theme: 'white', tag: 'Question fréquente', q: 'Comment suivre ma commande ?', a: 'Ouvrez votre tableau de bord : chaque commande affiche son étape actuelle. Vous recevez aussi une notification à chaque changement.',
    caption: 'Comment suivre sa commande ? Tableau de bord + notifications à chaque étape. C\'est tout. 📲', tags: `${H} #FAQ` },
  { day: 29, type: 'recap', theme: 'white', tag: 'En résumé', title: '6 raisons de choisir <em>KONVWA</em>', cells: [['wallet', 'Paiement en gourdes'], ['receipt', 'Devis transparent'], ['truck', 'Suivi complet'], ['camera', 'Photos du colis'], ['shield', 'Compte protégé'], ['phone', 'Appli sur mobile']],
    caption: 'En résumé : paiement local, devis transparent, suivi complet, photos du colis, sécurité, application mobile. Voilà pourquoi KONVWA. ✅', tags: `${H} #Récap` },
  { day: 30, type: 'cta', theme: 'navy', head: 'Prêt à <em>commander</em> ?', sub: 'Créez votre compte et envoyez votre premier lien.', cta: 'konvwa.shop',
    caption: 'Merci d\'avoir suivi ces 30 jours ! 🎉 Prêt à commander ? Créez votre compte et envoyez votre premier lien sur konvwa.shop', tags: `${H} #Alibaba #Shein #Temu #MonCash #NatCash` },
];
